---
title: Project Review  
author: Weifan Wu
date: "`r file.mtime(knitr::current_input())`"
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Modern Applied Data Analysis Project

Name of project author(s): Aidan Troha & Vijay Panthayi

Name of project reviewer: Weifan Wu



## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?


### Feedback and Comments

The manuscript is empty. I can find some information in README.md, but no basic background information or previous studies was provided.

### Summary assessment (PICK ONE, DELETE THE OTHERS)
* very poor contextualization and motivation



## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

The purposes of this study are stated clearly and they are closely related to the data sets retrieved.

### Summary assessment

* question/hypotheses fully clear


## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

Data is well-described and organized with the original source provided. Although there is no codebook, but the names of the variables in each raw data sets are fairly intuitive.

### Summary assessment

* source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

The data cleaning was well-done. All the variables and levels under each were renamed or converted to clean and east-to-understand format. In EDA part, only counts of some of the major variables were explored. In order to improve the visual presentations, it would be better to remove the "unknown" category,  incorporate additional aesthetic elements, and include descriptive titles. Furthermore, it is crucial to explore a greater number of relationships between variables to detect potential confounding factors that may impact the analysis.

### Summary assessment

* some weaknesses in wrangling and exploratory component




## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

Authors implemented LASSO approach to predict death counts based on party_majority, 2021 General Hospital Facilities, capital income, the number of graduates in 2020, and if there was more people graduate in 2020 than 2019. However, no justifications were stated regarding the selected predictors since there's no explorations about capital income or the number of graduates in 2020 in EDA section. The numbers of capital income could be transformed into log scales for better analysis. It was reasonable to choose Poisson regression since the outcomes are counts. However, linear regression and machine learning can also be included as alternative approaches to compare and refine the predictive models. 

### Summary assessment

* defensible but not optimal analysis 


## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The results were not organized into the manuscript. No table was presented and the figures are too simple.

### Summary assessment
* results are poorly presented, hard to understand, poor quality



## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

Discussion part is missing.

### Summary assessment
* major parts of discussion missing or wrong 



## Further comments


# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

The files seem to be organized into 6 main folders, but there are a lot of empty files including manuscript, readme.md, etc. The supplementary file contains irrelevant work from another project. Moreover, I couldn't find final manuscript which is supposed to contain the organized results, tables, and plots.

### Summary assessment

* mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

Each line of code was well-explained by plenty of comments in the Cleaning.R file. However, there is no comment in Fitting Models.R file.

### Summary assessment

* decently documented with some gaps


## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

All the results are reproducible with minimal interventions. 


### Summary assessment

* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

The exploratory data analysis was performed in a rather basic manner and failed to establish a meaningful connection to the subsequent process of model selection. Additionally, the model construction was limited to a single Poisson regression model, neglecting the consideration of alternative models. The discussion part is missing, therefore, there's no final discussion or statement addressing the research questions.

### Summary assessment
* weak level of thoroughness